const {useEffect,useState}=React;
const clean=(value,max=4000)=>String(value||'').replace(/[\u0000-\u001f]/g,'').trim().slice(0,max);
const safeJson=async r=>{try{return await r.json()}catch{return {error:'The server returned an unexpected response.'}}};
function App(){const [page,setPage]=useState(location.pathname==='/note-app'?'dashboard':'home');const [mode,setMode]=useState('login');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [notes,setNotes]=useState(()=>{try{return JSON.parse(localStorage.getItem('obsidian-notes'))||[]}catch{return []}});const [selected,setSelected]=useState(0);
useEffect(()=>{localStorage.setItem('obsidian-notes',JSON.stringify(notes))},[notes]);
async function auth(e){e.preventDefault();const f=new FormData(e.currentTarget),username=clean(f.get('username'),48),password=String(f.get('password')||'');if(username.length<3||!password.trim()){setMessage('Enter a username of 3+ characters and a password.');return}setBusy(true);setMessage('');try{const r=await fetch(mode==='login'?'/login':'/createAccount',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})}),data=await safeJson(r);if(!r.ok)throw new Error(clean(data.error,120)||'Could not continue.');location.assign('/note-app')}catch(err){setMessage(err.message||'Network error. Please try again.')}finally{setBusy(false)}}
function add(){setNotes(n=>[{id:crypto.randomUUID(),title:'Untitled note',content:'',updatedAt:Date.now()},...n]);setSelected(0)}function update(key,value){setNotes(n=>n.map((x,i)=>i===selected?{...x,[key]:clean(value),updatedAt:Date.now()}:x))}function remove(){setNotes(n=>n.filter((_,i)=>i!==selected));setSelected(0)}
if(page==='home')return <div className="shell"><nav className="nav"><div className="brand">OBSIDIAN <b>NOTES</b></div><div className="navlinks"><button className="button" onClick={()=>{setMode('login');setPage('auth')}}>Login</button><button className="button primary" onClick={()=>{setMode('signup');setPage('auth')}}>Sign up</button></div></nav><main className="hero"><div className="eyebrow">A PRIVATE SPACE FOR CLEAR THINKING</div><h1>Make room for what matters.</h1><p>A restrained workspace for ideas, plans, and the things worth keeping. Built for focus, not noise.</p><button className="button primary" onClick={()=>{setMode('signup');setPage('auth')}}>Start writing</button></main></div>;
if(page==='auth')return <div className="shell"><nav className="nav"><button className="brand" onClick={()=>setPage('home')}>OBSIDIAN <b>NOTES</b></button></nav><main className="auth"><form className="card" onSubmit={auth}><div className="tabs"><button type="button" className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Login</button><button type="button" className={mode==='signup'?'active':''} onClick={()=>setMode('signup')}>Sign up</button></div><h2>{mode==='login'?'Welcome back.':'Begin quietly.'}</h2><p className="muted">{mode==='login'?'Continue to your workspace.':'Create your private note space.'}</p><label className="field">Username<input name="username" autoComplete="username" maxLength="48" required/></label><label className="field">Password<input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength="6" required/></label><button className="button primary wide" disabled={busy}>{busy?'Please wait…':mode==='login'?'Login':'Create account'}</button><p className="message error">{message}</p></form></main></div>;
const current=notes[selected];return <div className="dashboard"><aside className="side"><div className="brand">OBSIDIAN <b>NOTES</b></div><button className="new" onClick={add}>+ New note</button><div className="notes">{notes.map((n,i)=><button key={n.id} className={'note '+(i===selected?'active':'')} onClick={()=>setSelected(i)}><strong>{n.title||'Untitled note'}</strong><small>{n.content||'Empty note'}</small></button>)}</div></aside><main className="editorwrap"><header className="top"><span>{current?'Saved locally':'No note selected'}</span>{current&&<button className="delete" onClick={remove}>Delete note</button>}</header><section className="editor">{current?<><input className="title" value={current.title} onChange={e=>update('title',e.target.value)} placeholder="Untitled note"/><textarea className="content" value={current.content} onChange={e=>update('content',e.target.value)} placeholder="Write something worth remembering…"/></>:<><h1>Your notes await.</h1><p className="muted">Create your first local draft.</p></>}</section></main></div>}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
